# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='themeid',
            field=models.ManyToManyField(blank=True, to='chat.Theme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='スタッフ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mailaddress',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス'),
        ),
    ]
